### ISSUE TITLE
Render fails when Object Names contain "|"

### ISSUE THREAD

**Issue by SimonStorlSchulke** [appleseedhq/blenderseed#218]
Whenever there is an | Symbol in an Objects name, the render will fail. To recreate thie Error, just rename the default cube to "|"
Blender 2.79b
Console Log:
```
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\render.py", line 64, in render
    self.__render_scene(scene)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\render.py", line 85, in __render_scene
    writer.write(scene, project_filepath)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\projectwriter.py", line 119, in write
    self.__emit_project(scene)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\projectwriter.py", line 144, in __emit_project
    self.__emit_scene(scene)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\projectwriter.py", line 157, in __emit_scene
    self.__emit_assembly(scene)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\projectwriter.py", line 169, in __emit_assembly
    self.__emit_objects(scene)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\projectwriter.py", line 301, in __emit_objects
    self.__emit_geometric_object(scene, object, False)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\projectwriter.py", line 335, in __emit_geometric_object
    self.__emit_dupli_object(scene, dupli_object[0], dupli_object[1], enable_object_blur)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\projectwriter.py", line 418, in __emit_dupli_object
    self.__emit_mesh_object_instance(scene, object, object_matrix, new_assembly)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\projectwriter.py", line 641, in __emit_mesh_object_instance
    for (material_index, mesh_name) in self._mesh_parts[object_name]:
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by jdent02** [comment]
It's not properly registering the __mesh_parts data when it exports the mesh to disk.  It works with a regular object name, right?

**Comment by jdent02** [comment]
So there's a very simple explanation for this error: '|' is a special character that can't be used in any Windows filepaths.  The exported mesh uses the object name, so in this case the mesh export fails because that character makes the filepath invalid so the mesh can't export.  That causes the render to fail.

**Comment by dictoon** [comment]
As discussed in Discord, we will fix this issue by replacing all reserved characters by underscores.

**Comment by jdent02** [comment]
FYI this one might take a while.  There's dozens of places where the object name is pulled (using object.name) and each of those occasions has to be located and the name modified.

**Comment by jdent02** [comment]
Covered in new python exporter
