### ISSUE TITLE
Can't enable

### ISSUE THREAD

**Issue by ScienceofSpock** [appleseedhq/blenderseed#26]
Windows 7 x64, Blender 2.77. I can install the add-on just fine, but when I try to enable it, I get an error message. This is copied from the console:
`Modules Installed from 'D:\\Downloads\\blenderseed_0.3.6_win64.zip' into 'C:\\Users\\keith.greene\\AppData\\Roaming\\Blender Foundation\\Blender\\2.77\\scripts\\addons' (blenderseed)
Traceback (most recent call last):
  File "D:\Blender Foundation\Blender\2.77\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\keith.greene\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\blenderseed\__init__.py", line 52, in <module>
    from . import properties
  File "C:\Users\keith.greene\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\blenderseed\properties\__init__.py", line 36, in <module>
    from . import nodes
  File "C:\Users\keith.greene\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\blenderseed\properties\nodes\__init__.py", line 33, in <module>
    from ...util            import addon_dir, join_names_underscore
ImportError: DLL load failed: The specified module could not be found.`

I am unsure how to proceed.

**Comment by dictoon** [comment]
Hello!

Unfortunately, due to a lack of resources, the Blender plugin is no longer developed and, sadly, no longer supported. We may one day revisit this decision and build a solid, full-featured plugin for Blender, but right now we are commited to bringing high quality appleseed integrations to 3ds Max, Maya and Gaffer.
