### ISSUE TITLE
Fail to activate blenderseed 1.0.0 on Ubuntu 16.04 after install

### ISSUE THREAD

**Issue by rchavp** [appleseedhq/blenderseed#396]
My settings:
Ubuntu 16.04
Blender 2.79b
Python version is 3.5 (sys.version_info(major=3, minor=5, micro=3, releaselevel='final', serial=0)
)

Error output from blender console (last 2 traces):

```
Modules Installed (blenderseed) from '/SAFE/DownloadStash/Blender/blenderseed-1.0.0-beta-linux64.zip' into '/home/ricardo/.config/blender/2.79/scripts/addons'

Traceback (most recent call last):
  File "/DATA/progs/blender-2.79b/2.79/scripts/modules/addon_utils.py", line 350, in enable
    mod.register()
  File "/home/ricardo/.config/blender/2.79/scripts/addons/blenderseed/__init__.py", line 56, in register
    preferences.register()
  File "/home/ricardo/.config/blender/2.79/scripts/addons/blenderseed/preferences.py", line 52, in register
    bpy.utils.register_class(AppleseedPreferencesPanel)
ValueError: register_class(...): already registered as a subclass
```

**Comment by jdent02** [comment]
Are you having an earlier failure to register the module?  Sometimes that can leave a bunch of junk left over and you'll get this error if you try to enable it again.

Can you provide a full log, starting from when you launch Blender?

**Comment by jdent02** [comment]
Any additional information on this one?

**Comment by jdent02** [comment]
Closing due to lack of feedback.
