### ISSUE TITLE
Connecting the Disney BRDF to the material output breaks rendering

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#45]
Reported here: https://blenderartists.org/forum/showthread.php?441610-Appleseed-1-8-0-beta-Released&p=3261844&viewfull=1#post3261844

**Comment by ejnaren** [comment]
I have same issue.
Following is the error report from the console:

---
Traceback (most recent call last):
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\render.py", line 70, in render
    self.__render_scene(scene)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\render.py", line 91, in __render_scene
    exporter.export(scene, project_filepath)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 119, in export
    self.__emit_project(scene)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 144, in __emit_project
    self.__emit_scene(scene)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 157, in __emit_scene
    self.__emit_assembly(scene)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 169, in __emit_assembly
    self.__emit_objects(scene)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 301, in __emit_objects
    self.__emit_geometric_object(scene, object, False)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 335, in __emit_geometric_object
    self.__emit_dupli_object(scene, dupli_object[0], dupli_object[1], ob_mblur)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 418, in __emit_dupli_object
    self.__emit_mesh_object_instance(scene, object, object_matrix, new_assembly)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 631, in __emit_mesh_object_instance
    self._emitted_materials[material] = self.__emit_material(material, scene)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 745, in __emit_material
    self.__emit_front_material(material, front_material_name, scene, layers, material_node, node_list)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 758, in __emit_front_material
    bsdf_name = self.__emit_front_material_bsdf_tree(material, material_name, scene, layers, material_node, node_list)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 801, in __emit_front_material_bsdf_tree
    self.__emit_disney_brdf(material, bsdf_name, 'front', None, node)
  File "C:\Users\ejnar\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blenderseed\project_file_writer.py", line 1133, in __emit_disney_brdf
    base_coat_name = inputs["Base Coat"].get_socket_value(True)
KeyError: 'bpy_prop_collection[key]: key "Base Coat" not found'

location: <unknown location>:-1
---
Attached is my system info.

[system-info.txt](https://github.com/appleseedhq/blenderseed/files/1546919/system-info.txt)

**Comment by dictoon** [comment]
Thanks @ejnaren, this issue will be fixed in the next beta that we will release shortly.

**Comment by jdent02** [comment]
#114

**Comment by jdent02** [comment]
Base color is called base coat in node parameter pull. Correcting names fixes issue.

**Comment by jdent02** [comment]
#118
