### ISSUE TITLE
ModuleNotFoundError: No module named 'appleseed._appleseedpython3'

### ISSUE THREAD

**Issue by dannybend** [appleseedhq/blenderseed#460]
Traceback (most recent call last):
  File "/home/danny/.config/blender/2.80/scripts/addons/blenderseed/appleseed/lib/appleseed/__init__.py", line 35, in <module>
    from _appleseedpythonbuiltin import *
ModuleNotFoundError: No module named '_appleseedpythonbuiltin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/blender/33/2.80/scripts/modules/addon_utils.py", line 384, in enable
    mod.register()
  File "/home/danny/.config/blender/2.80/scripts/addons/blenderseed/__init__.py", line 56, in register
    from . import preferences
  File "/home/danny/.config/blender/2.80/scripts/addons/blenderseed/preferences.py", line 30, in <module>
    import appleseed as asr
  File "/home/danny/.config/blender/2.80/scripts/addons/blenderseed/appleseed/lib/appleseed/__init__.py", line 45, in <module>
    from ._appleseedpython3 import *
ModuleNotFoundError: No module named 'appleseed._appleseedpython3'

**Comment by jdent02** [comment]
Where did you download the addon from?  Was it the official release or the master branch?

**Comment by dictoon** [comment]
Also, this appears to be Blender 2.80 on Linux, which we don't support at this time.

**Comment by jdent02** [comment]
Closing

**Comment by cgvirus** [comment]
Hello, is there any plan to launch in Linux with blender 2.8+?

**Comment by dictoon** [comment]
Properly supporting blenderseed on Linux requires some significant development efforts on our side. Hopefully we will get there at some point but we can't commit to a timeline.

**Comment by deltaray** [comment]
Hi, just putting this out there, not trying to start an argument. :smiley: A significant portion o the Blender community uses Linux and also Mac. Mostly focusing on Windows development might not align as well with the Blender community as it does on other 3D platforms.

**Comment by dictoon** [comment]
We're not focusing on Windows development, we support all three platforms. It's just that there are fundamental issues with how Linux and Blender deal with shared libraries that make it extremely challenging to provide binaries for Blender plugins (especially when it comes to a large plugin like blenderseed, which embeds the whole of appleseed and its dependencies).
