### ISSUE TITLE
Error when exporting appleseed scene from project with packed textures

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#502]
Repro case: [tests.zip](https://github.com/appleseedhq/blenderseed/files/4420647/tests.zip)

Error:
```
Traceback (most recent call last):
  File "C:\Users\Franz\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderseed\render\__init__.py", line 138, in render
    self.__render_final(depsgraph)
  File "C:\Users\Franz\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderseed\render\__init__.py", line 244, in __render_final
    scene_translator.translate_scene()
  File "C:\Users\Franz\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderseed\translators\scene.py", line 247, in translate_scene
    textures_to_add)
  File "C:\Users\Franz\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderseed\translators\scene.py", line 1007, in __create_entities
    mat.create_entities(self.bl_scene)
  File "C:\Users\Franz\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderseed\translators\material.py", line 71, in create_entities
    self.__as_nodetree.create_entities(bl_scene)
  File "C:\Users\Franz\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderseed\translators\nodetree.py", line 62, in create_entities
    self.__create_shadergroup(bl_scene)
  File "C:\Users\Franz\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderseed\translators\nodetree.py", line 114, in __create_shadergroup
    AssetType.TEXTURE_ASSET, sub_texture)
  File "C:\Users\Franz\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderseed\translators\assethandlers.py", line 135, in process_path
    shutil.copy(os.path.join(original_dir, filename), os.path.join(dest_dir, filename))
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\cg\\appleseed\\repro cases\\drachenseele_normals\\unnamed.png'
```

Unpacking the project before exporting fixes the issue.

**Comment by jdent02** [comment]
#452

**Comment by jdent02** [comment]
Closing this one as an alert was added that stops the render when packed textures are detected. A more robust solution might be a good idea at some point but it'll take some work to implement.
