### ISSUE TITLE
Enabling after install fails on Blender 2.93.4

### ISSUE THREAD

**Issue by stibinator** [appleseedhq/blenderseed#531]
I'm trying to install Blenderseed blenderseed-2.0.0-beta-0-g6b8f474
In the Blender prefs I install from the downloaded zip, the addon is loaded, but when I go to enable it I get this error:

[appleseed] Python path set to: C:\Users\stib\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderseed\appleseed\lib
[appleseed] Path to appleseed.dll is set to: C:\Users\stib\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderseed\appleseed\bin
Exception in module register(): C:\Users\stib\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderseed\__init__.py
Traceback (most recent call last):
  File "C:\Users\stib\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderseed\appleseed\lib\appleseed\__init__.py", line 35, in <module>
    from _appleseedpythonbuiltin import *
ModuleNotFoundError: No module named '_appleseedpythonbuiltin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "C:\Users\stib\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderseed\__init__.py", line 56, in register
    from . import preferences
  File "C:\Users\stib\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderseed\preferences.py", line 30, in <module>
    import appleseed as asr
  File "C:\Users\stib\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderseed\appleseed\lib\appleseed\__init__.py", line 45, in <module>
    from ._appleseedpython3 import *
ImportError: DLL load failed while importing _appleseedpython3: The specified module could not be found.

**Comment by ArsenoL** [comment]
same with 3.4

**Comment by IcedQuinn** [comment]
2.93 is marked as unsupported. I'm not sure what would be required to bring it up to date.
